image: docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  tags:
    - docker

  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - apk add --update git

  script:
    - export BRANCH=$(git name-rev --name-only HEAD)
    - export APP_ENV=$(if [ "$BRANCH" = "remotes/origin/develop" ]; then echo "dev"; else echo "prod"; fi)
    - export IMAGE_TAG=$(if [ ! -z "$CI_COMMIT_TAG" ]; then echo "$CI_COMMIT_TAG"; else echo "latest"; fi)
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG --build-arg app_env=$APP_ENV .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

deploy_dev:
  stage: deploy
  script:
    - apk add --update curl
    - curl
        --request POST
        --form "token=$DEPLOY_TOKEN"
        --form "variables[TRIGGER_APP]=mkapp"
        --form "ref=develop"
        https://gitlab.studiotwist.co/api/v4/projects/41/trigger/pipeline
  only:
    - develop
